#!/bin/bash
mpd 
mpDris2 &
xsetroot -cursor_name left_ptr &
# Coloring
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
bspc config border_width 0.5
## Bspwm configurations
bspc monitor -d 1:一 2:二 3:三 4:四 5:五 6:六 7:七 8:八 9:九 0:十 
bspc config focus_follows_pointer true
bspc config window_gap 12 
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 18
bspc config right_padding 8
bspc config bottom_padding 18
bspc config left_padding 8
bspc config border_radius 10
## Window rules
# remove all rules first
bspc rule -r *:*
# 1 > web
bspc rule -a Chromium desktop='^1' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^1' follow=on focus=on
# 2 > terminal and coding
bspc rule -a Urxvt desktop='^2' follow=on focus=on
bspc rule -a Gvim desktop='^2' follow=on focus=on
bspc rule -a code-oss desktop='^2' follow=on focus=on

# 3 > chat
bspc rule -a discord desktop='^3'  
# 4 > file
bspc rule -a Thunar desktop='^4' follow=on focus=on
bspc rule -a File-roller desktop='^4' follow=on focus=on
# 5 > office
declare -a office=(Geany Gucharmap Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done
# 5 > media
declare -a media=(Audacity mpv Gimp Gimp-2.8)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done
# 7 > settings
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done
bspc rule -a GParted desktop='^7' follow=on focus=on
# special rules
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a URxvt:urxvt_keys_help state=floating
$HOME/.config/bspwm/autostart.sh

